---
title: "Blogs"
listing: posts
---


<br> This page is work in progress! I will shortly start populating this with some of my work, projects and tidy-tuesday related code as times progresses. Enjoy!


<br> Tidy Tuesday 1: Here is the Tidy Tuesday where I looked through the Formula 1 dataset. 

* [Tidy Tuesday](formula/TidyTuesday_Formula1.html) 

<br> Tidy Tuesday 2: Here is the Tidy Tuesday where I looked through the Billboards dataset. 

* [Tidy Tuesday](billboard/Billboard_TT2.html) 


<br> Tidy Tuesday 3: Here is the Tidy Tuesday where I looked through the Nurses dataset: 

* [Tidy Tuesday](nurses/Nures_TidyTuesday3.html) 

<br> Tidy Tuesday 4: Here is the Tidy Tuesday where I looked through the Garden 2021 dataset: 

* [Tidy Tuesday](garden/TidyTuesday_4.html) 

<br> Tidy Tuesday 5: Here is the Tidy Tuesday where I looked through the Ultra Trail Running dataset: 

* [Tidy Tuesday](race/Tidy-Tuesday-5.html) 


"Without commitment you'll never start. Without consistency you'll never finish." - Denzel Washington
